// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	provider "github.com/knakul853/hookfire/internal/provider"
	mock "github.com/stretchr/testify/mock"
)

// MockCatalog is an autogenerated mock type for the Catalog type
type MockCatalog struct {
	mock.Mock
}

type MockCatalog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatalog) EXPECT() *MockCatalog_Expecter {
	return &MockCatalog_Expecter{mock: &_m.Mock}
}

// Events provides a mock function with given fields: _a0
func (_m *MockCatalog) Events(_a0 string) ([]string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalog_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type MockCatalog_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
//   - _a0 string
func (_e *MockCatalog_Expecter) Events(_a0 interface{}) *MockCatalog_Events_Call {
	return &MockCatalog_Events_Call{Call: _e.mock.On("Events", _a0)}
}

func (_c *MockCatalog_Events_Call) Run(run func(_a0 string)) *MockCatalog_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCatalog_Events_Call) Return(_a0 []string, _a1 error) *MockCatalog_Events_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalog_Events_Call) RunAndReturn(run func(string) ([]string, error)) *MockCatalog_Events_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields:
func (_m *MockCatalog) List() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockCatalog_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCatalog_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockCatalog_Expecter) List() *MockCatalog_List_Call {
	return &MockCatalog_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockCatalog_List_Call) Run(run func()) *MockCatalog_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCatalog_List_Call) Return(_a0 []string) *MockCatalog_List_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCatalog_List_Call) RunAndReturn(run func() []string) *MockCatalog_List_Call {
	_c.Call.Return(run)
	return _c
}

// Lookup provides a mock function with given fields: _a0, _a1
func (_m *MockCatalog) Lookup(_a0 string, _a1 string) (provider.Manifest, provider.Event, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Lookup")
	}

	var r0 provider.Manifest
	var r1 provider.Event
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (provider.Manifest, provider.Event, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) provider.Manifest); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(provider.Manifest)
	}

	if rf, ok := ret.Get(1).(func(string, string) provider.Event); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(provider.Event)
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCatalog_Lookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lookup'
type MockCatalog_Lookup_Call struct {
	*mock.Call
}

// Lookup is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *MockCatalog_Expecter) Lookup(_a0 interface{}, _a1 interface{}) *MockCatalog_Lookup_Call {
	return &MockCatalog_Lookup_Call{Call: _e.mock.On("Lookup", _a0, _a1)}
}

func (_c *MockCatalog_Lookup_Call) Run(run func(_a0 string, _a1 string)) *MockCatalog_Lookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockCatalog_Lookup_Call) Return(_a0 provider.Manifest, _a1 provider.Event, _a2 error) *MockCatalog_Lookup_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCatalog_Lookup_Call) RunAndReturn(run func(string, string) (provider.Manifest, provider.Event, error)) *MockCatalog_Lookup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCatalog creates a new instance of MockCatalog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalog {
	mock := &MockCatalog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
