// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	config "github.com/knakul853/hookfire/internal/config"
	mock "github.com/stretchr/testify/mock"
)

// MockSecretResolver is an autogenerated mock type for the SecretResolver type
type MockSecretResolver struct {
	mock.Mock
}

type MockSecretResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretResolver) EXPECT() *MockSecretResolver_Expecter {
	return &MockSecretResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function with given fields: source
func (_m *MockSecretResolver) Resolve(source string) (config.Secret, error) {
	ret := _m.Called(source)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 config.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (config.Secret, error)); ok {
		return rf(source)
	}
	if rf, ok := ret.Get(0).(func(string) config.Secret); ok {
		r0 = rf(source)
	} else {
		r0 = ret.Get(0).(config.Secret)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(source)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockSecretResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - source string
func (_e *MockSecretResolver_Expecter) Resolve(source interface{}) *MockSecretResolver_Resolve_Call {
	return &MockSecretResolver_Resolve_Call{Call: _e.mock.On("Resolve", source)}
}

func (_c *MockSecretResolver_Resolve_Call) Run(run func(source string)) *MockSecretResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSecretResolver_Resolve_Call) Return(_a0 config.Secret, _a1 error) *MockSecretResolver_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretResolver_Resolve_Call) RunAndReturn(run func(string) (config.Secret, error)) *MockSecretResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretResolver creates a new instance of MockSecretResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretResolver {
	mock := &MockSecretResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
