// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	http "net/http"

	sign "github.com/knakul853/hookfire/internal/sign"
	mock "github.com/stretchr/testify/mock"
)

// MockSigner is an autogenerated mock type for the Signer type
type MockSigner struct {
	mock.Mock
}

type MockSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSigner) EXPECT() *MockSigner_Expecter {
	return &MockSigner_Expecter{mock: &_m.Mock}
}

// Sign provides a mock function with given fields: body, opts
func (_m *MockSigner) Sign(body []byte, opts sign.SignOptions) (http.Header, error) {
	ret := _m.Called(body, opts)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 http.Header
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, sign.SignOptions) (http.Header, error)); ok {
		return rf(body, opts)
	}
	if rf, ok := ret.Get(0).(func([]byte, sign.SignOptions) http.Header); ok {
		r0 = rf(body, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, sign.SignOptions) error); ok {
		r1 = rf(body, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSigner_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockSigner_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - body []byte
//   - opts sign.SignOptions
func (_e *MockSigner_Expecter) Sign(body interface{}, opts interface{}) *MockSigner_Sign_Call {
	return &MockSigner_Sign_Call{Call: _e.mock.On("Sign", body, opts)}
}

func (_c *MockSigner_Sign_Call) Run(run func(body []byte, opts sign.SignOptions)) *MockSigner_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(sign.SignOptions))
	})
	return _c
}

func (_c *MockSigner_Sign_Call) Return(_a0 http.Header, _a1 error) *MockSigner_Sign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSigner_Sign_Call) RunAndReturn(run func([]byte, sign.SignOptions) (http.Header, error)) *MockSigner_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSigner creates a new instance of MockSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSigner {
	mock := &MockSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
