// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	fire "github.com/knakul853/hookfire/internal/fire"

	mock "github.com/stretchr/testify/mock"
)

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

type MockSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSender) EXPECT() *MockSender_Expecter {
	return &MockSender_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, req
func (_m *MockSender) Send(ctx context.Context, req *http.Request) (fire.Result, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 fire.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request) (fire.Result, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request) fire.Result); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(fire.Result)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *http.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - req *http.Request
func (_e *MockSender_Expecter) Send(ctx interface{}, req interface{}) *MockSender_Send_Call {
	return &MockSender_Send_Call{Call: _e.mock.On("Send", ctx, req)}
}

func (_c *MockSender_Send_Call) Run(run func(ctx context.Context, req *http.Request)) *MockSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockSender_Send_Call) Return(_a0 fire.Result, _a1 error) *MockSender_Send_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSender_Send_Call) RunAndReturn(run func(context.Context, *http.Request) (fire.Result, error)) *MockSender_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
